version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: restaurant-review-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant-review
    ports:
      - "5432:5432"
    volumes:
      - shared_pgdata:/var/lib/postgresql/data

volumes:
  shared_pgdata: