version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: restaurant-review-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: restaurant-review
    ports:
      - "5432:5432"
    volumes:
      - shared_pgdata:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant-review
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

  review-service:
    build: ./review-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/restaurant-review
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8081:8081"

volumes:
  shared_pgdata: